### ISSUE TITLE
Docs v0.1 - First Pass Feb 2017

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#12]
At the moment there are a lot of TODOs plus sections which are basically empty.

I suspect because this was copied from the OpenSpending docs and then had sections removed or cut down where no information was available.

## Tasks

* [x] Clean out old stuff
  * [x] WONTFIX Delete the users section (renamed to Publishera)
  * [x] Delete the contributors section

Improve the following sections:

* [x] Installation instructions to get started with the platform - this can mainly point to READMEs but if so check those READMEs are up to date 
  * [x] #13 - general instructions
    * [x] #15 - s3 setup instructions
    * [x] #14 - auth0 setup WONTFIX
* [x] CLI - this is basically empty atm. #16

## TODO - unfinished and will be done as part of another epic

* [ ] API Docs - this does not need to detail every method as that is in the swagger stuff online. However, it should give some context and point to swagger docs and other relevant docs, give an overview and link to things like auth
  * #18 
* [ ] Architecture - explain the high-level architecture (diagram welcome) - we can take most of this from [existing architecture google doc][arch] and associated diagrams  #19

[arch]: https://docs.google.com/document/d/1uqvk5va5Js-XUtqTn-uG4NNAsTYioq2dilmQVUiNXhc/edit

**Comment by Fak3** [comment]
@rufuspollock 
> Isuggest we:
> Delete the contributors section
> ...
> Explain what CLI is and how you can use it to publish data packages

I am not sure about the deletion of 'contributors' section. It was here to split the publishers doc from internals targeted for developers. I suggested to rename it to 'publishers' in #9 before. So the CLI **usage** docs should go in there, as those really target the publihers, not the developers. 

Right now the 'contributors' section has step-by step structure for publishers: 
* Prepare (csv and other raw data formats overview and recommendations)
* Package (create and validate DataPackage using CLI or other validation tools)
* Upload to registry (using CLI or webui)

I think the cli docs could fit into this structure.

**Comment by rufuspollock** [comment]
@Fak3 - contributors section was copied from OpenSpending. If you want to keep it then:

- Rename to publishers
- Delete everything in it atm and just have the CLI docs (Yes, some of the content is relevant but it is not worth sorting through that right now and I'm not that interested in doing proper publisher docs - i just want CLI doc'd here in a minimal way so we have info in one place)

**Comment by rufuspollock** [comment]
FIXED. Largely done and now quite old. Remaining items will be part of new epic #25 and related subissues.
