### ISSUE TITLE
Add API Docs

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-docs#18]
Page documenting the overall API.

## Acceptance criteria

- [x] We have nicley documenting API, either embeded or linked to current swagger docs.

## Tasks

- [x] Short intro
- [x] Try out if it is possible to embed swagger in mkdocs
  - [x] If yes Embed swagger API inside docs

Extras:

* [x] Maybe move the swagger location from http://staging.datapackaged.com/spec to http://staging.datapackaged.com/api/swagger.json
* [ ] <del>Move API docs location on main site to https://staging.datapackaged.com/apidocs/ from https://staging.datapackaged.com/apidocs/index.html</del>
* [x] TODO: Or even remove entirely if we have them in the docs site (and link from navbar to docs site ...)

**Comment by zelima** [comment]
FIXED we embedded swagger API.

Estimated: 3h was 6h (with pair programming)
