### ISSUE TITLE
Clean out all the old stuff and get us back to a skeleton

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-docs#24]
We need to delete old pages from docs that are not relevant anymore.

## Tasks

Note: we can borrow a lot from https://github.com/openspending/docs - http://docs.openspending.org/en/latest/

### Developers

* [x] DELETE https://frictionlessdata.github.io/dpr-docs/developers/platform/ NOT COMPLETE
	* everything except "Contributing code" part is TODO
* [x] DELETE https://frictionlessdata.github.io/dpr-docs/developers/api/ NOT COMPLETE 
	* Missing Installation guide (is this needed at all?).
	* Only one bullet point in`Features`
* [x] DELETE https://frictionlessdata.github.io/dpr-docs/developers/cli/ NOT COMPLETE / OUTDATED 
	* Is Datapackage one word or two?
	* says dpmpy 
	* No guide for installation
* [x] KEEP (and update) https://frictionlessdata.github.io/dpr-docs/developers/authentication/ OUTDATED
	* says dpm-py
	* We are not using outh0 any more
* [x] DELETE https://frictionlessdata.github.io/dpr-docs/developers/infrastructure/ OUTDATED
	* The whole infrastructure is not built on AWS any more. We use Heroku and Claudflare 
	* No AWS API gateway any more
	* No cloudfront any more
* [x] DELETE data store: https://frictionlessdata.github.io/dpr-docs/developers/datastore/

Worth keeping:

- developers: https://frictionlessdata.github.io/dpr-docs/developers/
- authorization: https://frictionlessdata.github.io/dpr-docs/developers/authorization/

### Publishers

* [x] Tidy up based on changes  https://frictionlessdata.github.io/dpr-docs/publishers/ OUTDATED
  * `dpm-py` instead of just `dpm`
* [x] DELETE https://frictionlessdata.github.io/dpr-docs/publishers/prepare/ OUTDATED
  * again `dpmpy` instead of just `dpm`
  * it says we use `GoodTables data validator`, do we?
  * there is [TODO] in Minimum quality requirements section
* [x] DELETE https://frictionlessdata.github.io/dpr-docs/publishers/package/ NOT COMPLETE
  * Packaging data Manually section is empty
  * is **creating dp manually** the only option?
* [x] DELETE https://frictionlessdata.github.io/dpr-docs/publishers/upload/ NOT COMPLETE
  * Packaging data Manually section is not done
* [x] DELETE https://frictionlessdata.github.io/dpr-docs/publishers/use/ EMPTY / NOT COMPLETE
* [x] KEEP and merge with main page https://frictionlessdata.github.io/dpr-docs/publishers/cli/ OUTDATED but good
  * typo in heading of the page - Manager
  * again `dpmpy` instead of just `dpm`

**Comment by zelima** [comment]
FIXED
