### ISSUE TITLE
[epic] Docs v0.2

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#25]
As Rufus I want to improve our technical docs so that:

* We understand what we are doing technically (by doing the docs we understand the current system and where we are going)
* Others can understand what we are doing technically (e.g. we can onboard new devs more easily)
* Publishers have documentation to help them publish to the DataHub
  * And by writing these docs we think through what it is like for a new publisher - "Documentation Driven Development"
* ~~Consumers have documentation to help them get data from the DataHub~~ - not a priority for now

## Acceptance Criteria

* [x] No TODOs, incomplete sections in the docs
* [x] Publisher could get started just by reading our docs
* [x] Technical architecture is clear enough to explain effectively to e.g. Jo or a newcomer (they can answer basic questions, they say they understand)

### Planning

* [x] Read section on docs in [DataHub README][dh-readme]
* [x] Review website and identify what to keep and what to delete
* [x] Review existing epic and issues
* [x] Identify what content we want to add and its priority
  * See diagram in DH README

### Clean Up and Prep

* [x] Create a proper README - #26
* [x] Add mermaid and fontawesome support - #27
* [x] Clean out old stuff and get us back to a skeleton - #24

### MVP Docs

* [x] Publisher: Walkthrough on publishing a data package #28
* [x] Developer: `/install/` Local install (so you can start coding). Super simple: a few words and then we can just link to the dpr-api README
* [x] Developer: platform architecture #31
  * key concepts
  * overview of main components and how they fit together
* [x] Developer (DevOps): Production Deploy of the platform `/deploy/` #30 
  * Intro sentence / paragraph
  * Outline deployment architecture
  * How to do deployment - link to dpr-deploy on gitlab
* [x] Developer: API `/api/` #18 
  * [x] Embed swagger if possible
* [x] Developers: publishing flow: `/publish/` #32 
  * [x] sequence diagram
  * [x] explain the dieagram

**Comment by zelima** [comment]
@rufuspollock all the issues inside this Epic is fixed now, is there anything remaining besides these? If not we can close

**Comment by rufuspollock** [comment]
FIXED. See http://docs.datapackaged.com/
