### ISSUE TITLE
README has no local build instructions

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-docs#26]
Key information is missing how to build this locally 

## Acceptance criteria

- [x] someone unfamiliar with docs can build locally without help

## Tasks

- [x] Need explanations of what this repo does
- [x] Instructions for how to build docs locally is missing
- [x] How it gets deployed

**Comment by zelima** [comment]
FIXED
