### ISSUE TITLE
[publisher] Walkthrough on Publishing a Data Package

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#28]
Adequate and succinct instructions for a publisher to publish their data package.

https://frictionlessdata.github.io/dpr-docs/publishers/

For now this can be quite terse and simple as more for us to think through the steps than as actual tutorial (and no screenshots etc).

## Acceptance criteria

* [x] Complete walkthrough of publishing a data package on the DataHub
* [x] Assumption clearly marked

## Tasks

* [x] Sign up & get secret key
* [x] Install command line tool
* [x] Configure
* [x] Publish a file
  * Assumption: you know what a data package is
* [x] View it online

In dpmpy:

* [x] Usage section: Remove usage instructions here and link to this tutorial /publishers/ so that we avoid duplication
* [x] Create Developer section with clone, setup and test instructions

**Comment by zelima** [comment]
FIXED
