### ISSUE TITLE
Docs for deploy 

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-docs#30]
Instructions for how to deploy app on `/deploy/` page 

## Acceptance criteria 

* [ ] developer is able to deploy following the docs (without any other help)

## Tasks 

* [x] create Intro sentence / paragraph
* [x] Outline deployment architecture
* [x] How to do deployment - link to dpr-deploy on gitlab

**Comment by zelima** [comment]
FIXED
