### ISSUE TITLE
[dev] Platform Architecture overview

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#31]
We need nice page explaining platform architecture. 

## Acceptance criteria

- [ ] simple and easy to understand 

## Tasks

* [x] Domain Model - diagram (material from old tech arch diagram)
* [x] Overall architecture (diagram)
* [x] List of components
  * Short description
  * Link to repo or subpart of repo (for blueprints)

## Analysis

Drive Architecture folder: https://drive.google.com/drive/folders/0B4VpjxPkN_XcSlpfanBqd042YlU

Our up to date version for DataHub

Service Architecture
#
![image](https://cloud.githubusercontent.com/assets/15143785/25481196/26488996-2b5d-11e7-839c-335c031c43b0.png)

**Comment by zelima** [comment]
FIXED Platform page is live https://frictionlessdata.github.io/dpr-docs/developers/platform/

**Comment by zelima** [comment]
Some tidy-up and polishing still needed for this page

**Comment by zelima** [comment]
FIXED
