### ISSUE TITLE
Developer: Publishing Flow

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-docs#32]
As a Developer I want to understand the publishing flow so that I understand one of the core operations of the system (and one that touches many other systems such as auth, cli, authz etc)

`/publish/`

## Acceptance Criteria

* [x] We have sequence diagram illustrating the whole flow from a client (e.g. CLI) perspective
* [x] We have explanations for each step in sequence diagram

## Tasks

* [x] create a new sequence diagram using mermaid like the one in this issue  https://github.com/frictionlessdata/dpr-api/issues/2
* [x] understand the flow (go through the [code in dpmpy][dpm])
* [x] Explanation and/or links to docs or systems for each step from perspective of client
  * [x] Authentication
    * Docs
    * Link into API docs
  * [x] Authorization API
    * Docs / link
* [x] Explanation of internal system
  * [Metadata and Data flow diagram][flow]
    * [x] Convert to mermaid
    * [x] Colour to illustrate what parts exist
  * [x] Auth from internal perspective
  * [x] Authorization from internal perspective
    * Internal docs (basically current authorization docs we have)
  * [x] ~~Metastore~~
  * [x] BitStore
  * [x] DataStore (does not exist yet)

[flow]: https://docs.google.com/a/datopian.com/drawings/d/1sVxx0wDNNxtquy33m8Feo_3S5c8LAvBBLHyuTcxSUqA/edit?usp=drive_web
[dpm]: https://github.com/frictionlessdata/dpm-py/blob/master/dpm/client/__init__.py#L120

**Comment by zelima** [comment]
FIXED. see https://frictionlessdata.github.io/dpr-docs/developers/publish/
