### ISSUE TITLE
[dev] DataHub views

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-docs#37]
Write up introduction page for developers on DPR-JS so they can quickly understand purpose and concepts of the module.

## Acceptance criteria

* [x] Clear introduction into dpr-js
* [x] mermaid diagram showing how the module works
* [x] key links

## Tasks

* [x] create a new page `views.md`
* [x] create mermaid diagram
* [x] write intro text + some notes + have links for dpr-js, datapackage-render-js, views spec and analysis pad

**Comment by anuveyatsu** [comment]
FIXED
