### ISSUE TITLE
Deploy docs to a docs.datapackaged.com

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#39]
Deploy the docs to a nicer domain: docs.datapackaged.com (later may move again but this is good for now)

## Acceptance criteria

* [x] Docs are live at docs.datapackaged.com

## Tasks

* [x] Add record in cloudflare to point to relevant part of github.io for github pages for this repo
* [x] Change CNAME here
* [x] Change link in dpr-api config

**Comment by zelima** [comment]
FIXED live on https://docs.datapackaged.com
