### ISSUE TITLE
Move user stories to hackmd from google docs

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#40]
Get user stories in one location - currently have hackmd and google docs. We are also converging on hackmd as markdown based and open.

## Acceptance criteria

* [x] Docs are in hackmd

## Tasks

* [x] Download and convert to markdown from pandoc
* [x] Paste into hackmd
* [x] Tidy

**Comment by rufuspollock** [comment]
FIXED. All Done!
