### ISSUE TITLE
Move core data curators docs here

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#41]
This is the main page: http://data.okfn.org/roadmap/core-datasets

* Main page source: https://github.com/okfn/data.okfn.org-new/blob/master/views/core-datasets.html
  * Note: the general summary (i.e. hero section at top) would make more sense as description for core publisher on main datahub site.
* http://data.okfn.org/doc/core-data-curators 
  * https://github.com/okfn/data.okfn.org-new/blob/master/doc/core-data-curators.md

Bonus points: incorporate / move over http://okfnlabs.org/blog/2015/01/03/data-curators-wanted-for-core-datasets.html

## Acceptance criteria

* [x] New item under publishers for core-datasets initiative
 * [x] Includes both introduction to the initiative and instructions for getting involved and steps in doing this

## Tasks

* [x] Create a core-datasets page for publisher
* [x] Include an intro (more based on okfnlabs blog post and roadmap page)
* [x] Include the full tutorial section

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-docs/pull/42

**Comment by rufuspollock** [comment]
@anuveyatsu / @Mikanebu when closing it is really useful to link to the result e.g. the docs live on the site 😉

**Comment by anuveyatsu** [comment]
@rufuspollock here is the link - http://docs.datapackaged.com/publishers/core-datasets/

**Comment by rufuspollock** [comment]
@Mikanebu good work copying this across. Much of the material looks to be there.

What you want to ask yourself: does this make sense to me? Would this make sense to someone turning up on this page? (Would they know what was going on?)

Big:

* [x] Introduction to what Core Datasets are is very limited compared to explanation in the blog post or the old site. This need to be really clear at the start of the page.
  * [x] no embedding of the useful intro slide deck (or if not embedding pull out the key points).
  * [x] No call to action at the bottom leading into the guide
* [x] Core data curators guide has no introduction of explanation. What is it? Who is it for? etc.
  * [x] Personally, I'd have had the guide in a separate page with a call to action link from main core datasets page to the core data curators page (but you could argue this either way).

Small

* [x] the docs still include links to the data.okfn.org site e.g. in list at the topc http://data.okfn.org/roadmap/core-datasets - the point of this move was to have everything here (we are about to shut down data.okfn.org!)
* [x] diagram overflows the width of the page

**Comment by Mikanebu** [comment]
@rufuspollock The slide deck has a link to the http://data.okfn.org/roadmap/core-datasets. 
Do I have to change it to the http://docs.datapackaged.com/publishers/core-datasets/ since that one is going to shut down?

**Comment by Mikanebu** [comment]
FIXED in #43
