### ISSUE TITLE
[EPIC] Documentation for views and transforms

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-docs#44]
We need documentations about using views and transforms in a descriptor. This documentation would help publishers to understand how they can include views in their data packages.

## Acceptance criteria

* [ ] clear documentations on using data package `views` so anybody familiar with data packages can understand
* [ ] clear documentations on using transforms so anybody who is familiar with data packages can understand

## Tasks

* [x] docs on views - #45 
* [x] docs on transforms - #46

**Comment by anuveyatsu** [comment]
Mostly FIXED, however, example links are hard coded at the moment, we need to handle it somewhere in config variables. So leaving this epic as open and moving to next milestone. Fixes can be implemented against this epic and should not take more than 1h.
