### ISSUE TITLE
Docs for publishers on using data package views

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-docs#45]
Thorough docs for publishers on how to use `views` in their Data Packages. This section should go under `Publishers` section on docs site.

## Acceptance criteria

* [x] clear explanation on using views

## Tasks

* [x] write introduction paragraph explaining purpose of docs and its capabilities
* [x] explain views as graphs
* [x] write about simple views
* [x] write about vega views
* [x] write about table views

**Comment by rufuspollock** [comment]
@anuveyatsu could this be closed?

**Comment by anuveyatsu** [comment]
FIXED in #47
