### ISSUE TITLE
Docs for publishers on using transforms in views

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-docs#46]
Thorough docs on how to use transform in data package views. This should help publishers to understand and start using transforms in their data packages.

## Acceptance criteria

* [x] clear explanation on using data transforms

## Tasks

* [x] Introduction paragraph about data transforms
* [x] Aggregation, Filter, Formula, Sample - explanation + examples

**Comment by anuveyatsu** [comment]
FIXED in #47
