### ISSUE TITLE
Update and Add instructions on CLI

### ISSUE THREAD

**Issue by Mikanebu** [frictionlessdata/dpr-docs#48]
We want to have an updated version of CLI page for using new CLI.

## Acceptance criteria

* [x] We have an updated version of the CLI page

## Tasks
* [x] Update CLI page
  * [x] Getting started section
  * [x] Installation
  * [x] Commands
  * [x] Configuration
  * [x] Links

**Comment by Mikanebu** [comment]
FIXED in #49
