### ISSUE TITLE
[epic] Update docs for new DataHub 

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#50]
* [x] Dev docs
  * [x] API Docs (consolidated in one place)
  * [x] Installation
  * [x] Architecture
* [x] Publisher
  * [ ] Intro to resources and datasets, Data Resource and Data Packages
  * [ ] Essentials of data packages and how to publish
    * [ ] cf this stuff here http://frictionlessdata.io/guides/publish/
  * [ ] (?) publish using CLI

**Comment by zelima** [comment]
FIXED closing as all the issues inside Epic are closed. republisher page:

> Publishers docs are now on main site and managed in frontend repo.
