### ISSUE TITLE
API docs for new DataHub

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#51]
Current API is for DPR and we want to update for new DataHub (DataHub new v1 or DataHub v2 if you like)

Based it on http://docs.openspending.org/en/latest/developers/conductor/ and replace our current API page which uses swagger embed.

Hackmd with docs here: https://hackmd.io/IYDgbGAsYJwIwFowGMAMkGQCYDMBMCIRMCWAzGWHDKjpDjDEA===?both#datahubio-api-analysis

## Acceptance criteria

* [x] Intro with outline of the API structure (plus definition of primary location api.datahub.io etc)
* [x] Docs for auth API (copy from main README)
* [x] Docs for bitstore API (from hackmd i think)
* [x] Rough docs for specstore API

## Tasks

* [x] auth
* [x] bitstore
* [x] specstore
* [?] assembler

**Comment by Mikanebu** [comment]
FIXED
