### ISSUE TITLE
Update Installation and Architecture sections for new DataHub

### ISSUE THREAD

**Issue by Mikanebu** [frictionlessdata/dpr-docs#54]
We want to update installation and architecture section for developers for new DataHub. 

## Acceptance criteria

* [x] Updated installation section with all repo readme links 
* [x] Updated architecture section with new DataHub 

## Tasks

* [x] Link all readme into Installation section
* [x] Update diagrams in architecture section

**Comment by Mikanebu** [comment]
FIXED
