### ISSUE TITLE
Update docs for new DataHub publisher's section

### ISSUE THREAD

**Issue by Mikanebu** [frictionlessdata/dpr-docs#56]
We want to update section for publishers for new DataHub. 

## Acceptance criteria
* [ ] Update getting started page
* [ ] Intro to resources and datasets, Data Resource and Data Packages
* [ ] Essentials of data packages and how to publish 
  * [ ] cf this stuff here http://frictionlessdata.io/guides/publish/

## Tasks

* [ ] Updated getting started page 
* [ ] Updated intro to resources and datasets, Data Resource and Data Packages
* [ ] Added essentials of data packages and how to publish 

## Analysis 

* getting started
	* Sign up & get a secret key
		* You can sign up with google account as well
		* No access token or secret key is provided on dashboard
	* Install command line tool
		* Totally outdated - still instructions for dpm.py
		* same with configure
	* Publish a dataset
		* Outdated - dpm instructions
* Core datasets
	* Pointing to http://datapackaged.com/core/
* Core Data Curators Guide
	* Quick links
		* this should probably be sub bullet point "his is the place to ask questions, get help etc - just open a new topic
		* "Publish Data Packages Howto on Frictionless Data Site" - wired sentence, maybe _"How to Publish Data Packages on Frictionless Data Site"_
	* Preparing Datasets as Core Data Packages
		* Publishing section outdated as from now on it will be datahub.io
* CLI
	* Getting started
		* `Remove uploaded Data Package from DataHub` not supported
		* supported but not present
			* Login
			* Cat
	* Installation
		* "without npm"? think "Installing binaries" is enough
		* `mv path/to/data-{os-distribution} /usr/local/bin/data` is not enough I had to run `chmod -X /usr/local/bin/data` as well (linux)
		* For installing with npm We should sprcify the version of `Nodejs` as we do not support all of them
		* `npm install -g data` or `npm install -g datahub-cli` (as that's how it is called in pckage.json)
		* Before `npm install...` think we should say to clone the repo and run `npm install...` after. 
			* Also link to repo is not present
	* Commands
		* `data --help` actually errors with `Command does not exist "--help"`
			* so does `data -help`
			* so does `data -h`
		* List of commands outdated - we do not  have purge and `cat` or `login` are not there
	* Configuration
		* `data config[ure]` - does not exist
		* place configurations are saved is outdated
		* Format of config file outdate (not json)
		* Actuall content of configfile is outdated
	* Usage
		* you can do much more with `data push` rather than just push the datapackage 
		* You do not have to go to the directory (can indicate path)
		* I don't think we need this: 
			* >If your configured username and secretToken are correct, data will upload datapackage.json and all relevant resources to the DataHub server.
		* Delete is extra
		* cofigure is extra
		* login is missing
		* cat si missing
	* link
		* `Code repo` ???
* Views
	* Links are outdated (pointing to datapackaged.com)

**Comment by rufuspollock** [comment]
INVALID / WONTFIX. Publishers docs are now on main site and managed in frontend repo.
