### ISSUE TITLE
Update api docs

### ISSUE THREAD

**Issue by Mikanebu** [frictionlessdata/dpr-docs#57]
Current API section is outdated and needs link to the all  API

## Acceptance criteria

* [x] Each service has documentation of its API in its README
  * [x] Identify any common patterns we could extract (e.g. around error responses) and summarize in this issue
* [x] API section in docs has headings for each service and a link to the README for it

## Tasks

Each of these services has API documented in README and each has an entry in the API docs with a link to that README:

* [x] auth - https://github.com/datahq/auth#api
* [x] specstore (assembler?) - https://github.com/datahq/specstore#api
* [x] bitstore (rawstore in docs) - https://github.com/datahq/bitstore#api
* [x] metastore https://github.com/datahq/metastore/pull/6 - https://github.com/datahq/metastore#api
* [x] resolver https://github.com/datahq/resolver/issues/3 - https://github.com/datahq/resolver#api
* [x] docs API section - http://docs.datahub.io/developers/api/

**Comment by Mikanebu** [comment]
FIXED

**Comment by rufuspollock** [comment]
FIXED.
