### ISSUE TITLE
Updates to dev docs as of 17 Aug 2017

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#60]
Updates to developer docs that are needed to be up to date:

* [getting started] missing resolver in list of platforms (as well in diagram and install part)
* [platform] same here
* publish docs are out of date and need an update
* Authorization and Authentication should be deleted and references to them deleted 

## Acceptance criteria

* [ ] Updated developer docs

## Tasks

* [x] Updated `getting started` page
* [x] Removed `Authorization` and `Authentication`
* [x] Developer `publish` update
* [x] Developer `platform` update

**Comment by Mikanebu** [comment]
FIXED
