### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-docs#61]
We want to setup Google analytics in our documentation site `docs.datahub.io`

## Acceptance criteria

* [x] GA property added into `mkdocs.yml`

## Tasks

* [x] Create new Tracking ID for `docs.datahub.io`
* [x] Add Tracking ID into `mkdocs.yml`

## Analysis: 

*  create GA key for docs, it should be different from `datahub.io`
*  see configuration mkdocs about GA analytics
  http://www.mkdocs.org/user-guide/configuration/

**Comment by Mikanebu** [comment]
FIXED
