### ISSUE TITLE
Redirect or remove publishers section and add diagrams into developer section

### ISSUE THREAD

**Issue by Mikanebu** [frictionlessdata/dpr-docs#73]
We want to redirect if it is possible or remove publishers section, plus add diagrams into developer section

## Acceptance criteria

* [x] `Publishers` section redirected or removed
* [x] Added diagrams `diagram for upload process` and `Identity Pipeline` into `developers/publisher` page

## Tasks

* [x] Do analysis on redirecting `publishers` section
  * [x] if yes, redirect
  * [x] else remove 
* [x] Add diagrams `diagram for upload process` and `Identity Pipeline` into `developers/publisher` page

## Analysis 

Since our docs site is built by mkdocs lib. It does not support redirection. Tried to modify `mkdocs.yml` by providing absolute path. It throws error. 
Issue is still open in their github repo:
https://github.com/mkdocs/mkdocs/issues/989.

**Comment by Mikanebu** [comment]
FIXED, publishers section removed, added diagrams for` upload process` and `Identity Pipeline` into developers/publisher page
